name: CI

on:
  push:
    branches:
     - master

jobs:
  client:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          WEBGPU_ORIGIN_TRIAL: ${{ vars.WEBGPU_ORIGIN_TRIAL }}
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - id: deployment
        uses: actions/deploy-pages@v1
